/*
   Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
*/
flagres=true;function widthWinId(){var width_win=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;if(width_win>991){if(!flagres)flagres=true}else if(flagres)flagres=false}function height_name(){var column=$j(".products-grid li.item .product-name"),maxHeight=0;if(!flagres)$j(column).removeAttr("style");else{column.each(function(){$j(this).removeAttr("style");if($j(this).outerHeight()>maxHeight)maxHeight=$j(this).outerHeight()});column.outerHeight(maxHeight)}}
function hide_accordion(){idClick=".id-click";idSlide=".id-block";idClass="id-active";$j(idClick).on("click",function(e){e.stopPropagation();var subUl=$j(this).next(idSlide);if(subUl.is(":hidden")){subUl.slideDown();$j(this).addClass(idClass)}else{subUl.slideUp();$j(this).removeClass(idClass)}$j(idClick).not(this).next(idSlide).slideUp();$j(idClick).not(this).removeClass(idClass);e.preventDefault()});$j(idSlide).on("click",function(e){e.stopPropagation()});$j(document).on("click",function(e){e.stopPropagation();
var elementHide=$j(idClick).next(idSlide);$j(elementHide).slideUp();$j(idClick).removeClass("id-active")})}
function hide_settings(){elementClick=".select-store-icon";elementSlide=".select-store-switcher > ul";elementClass="id-active";$j(elementClick).on("click",function(e){e.stopPropagation();var subUl=$j(this).next(elementSlide);if(subUl.is(":hidden")){subUl.slideDown();$j(this).parent().addClass(elementClass)}else{subUl.slideUp();$j(this).parent().removeClass(elementClass)}$j(elementClick).not(this).next(elementSlide).slideUp();$j(elementClick).not(this).parent().removeClass(elementClass);e.preventDefault()});
$j(elementSlide).on("click",function(e){e.stopPropagation()});$j(document).on("click",function(e){e.stopPropagation();var elementHide=$j(elementClick).next(elementSlide);$j(elementHide).slideUp();$j(elementClick).parent().removeClass(elementClass)})}
function hide_settings_right(){elClick=".elClick";elSlide="elSlide";elClass="id-active";$j(elClick).on("click",function(e){e.stopPropagation();if($j(this).parent().hasClass(elClass))$j(this).parent().removeClass(elClass);else $j(this).parent().addClass(elClass);$j(elClick).not(this).next(elSlide).removeClass(elClass);$j(elClick).not(this).parent().removeClass(elClass);e.preventDefault()});$j(elSlide).on("click",function(e){e.stopPropagation()});$j(document).on("click",function(e){e.stopPropagation();
var elHide=$j(elClick).next(elSlide);$j(elHide).removeClass(elClass);$j(elClick).parent().removeClass(elClass)})}function cursor_search(){if(flagres)$j(".header-search .account-dropdown").on("click",function(){$j("#search").focus()})}function index_pages(){if($j(".cms-index-index").length)if(!$j(".widget.sliderClass").length)$j("body").addClass("overflow-disable")}function enableStickUp(){if(flagres){if($j(".page-header-container").length)$j(".page-header-container").tmStickUp();return false}}
function hide_filter(){$j(".filter-click").on("click",function(e){e.stopPropagation();if($j(this).parent().hasClass("filter-hide"))$j(this).parent().removeClass("filter-hide");else $j(this).parent().addClass("filter-hide");$j("filter-click").not(this).parent().removeClass("filter-hide");e.preventDefault()})}
$j(document).ready(function(){hide_settings();hide_settings_right();hide_accordion();index_pages();hide_filter();$j(window).bind("load resize",function(){clearTimeout(this.id);this.id=setTimeout(widthWinId,300);this.id=setTimeout(height_name,300);this.id=setTimeout(cursor_search,300)})});
